# Generated by Django 5.0.14 on 2025-06-13 00:13

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ruta_fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.get_unique_filename),
        ),
    ]
