# Generated by Django 5.0.14 on 2025-06-13 00:18

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ruta_fotografia',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.utils.get_unique_filename),
        ),
    ]
